### PR TITLE
Docker: upgrading to 17.03 engine version

### PR DESCRIPTION
**Pull request by bryanlatten**
Also removes deprecated `daemon`option

### CODE REVIEW

**Comment by bryanlatten** [comment]
Even though 1.12.6 version works properly, there is a warning message from CoreOS stable channel:
```time="2017-03-15T04:35:49.662040204Z" level=warning msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"```

Release notes for 17.03 specify fix for stdin closure. Upgrading!

**Comment by ssk2** [comment]
Hi @bryanlatten, did you get a chance to try 1.13? Since that is the officially supported Docker version for DC/OS 1.9, I'd like to avoid bumping the version beyond that until we upgrade the base dependency. Is that workable? (I haven't had a chance to try 1.13 - might this fix the warning message?)

**Comment by bryanlatten** [comment]
I'll give it a shot, but as per their new release process, these monthly releases are bugfixes only, no API changes or additions. This one stands out: https://github.com/docker/docker/pull/31070

**Comment by bryanlatten** [comment]
👍  Other than some (existing) modprobe issues, looks good on 1.13.1 as well (pushed to my hub as 0.4.1-ubuntu/alpine)

```core@core-01 ~ $ docker run --privileged bryanlatten/dcos-jenkins-dind-agent:0.4.1-ubuntu wrapper.sh "java -version && docker run hello-world"
Unable to find image 'bryanlatten/dcos-jenkins-dind-agent:0.4.1-ubuntu' locally
0.4.1-ubuntu: Pulling from bryanlatten/dcos-jenkins-dind-agent
e2d7e96004fd: Pull complete
1bacd3c8ccb1: Pull complete
869d5d3f92f8: Pull complete
f8a4e25b40ce: Pull complete
f40e1388890a: Pull complete
b027f5664222: Pull complete
1af7d116c2cf: Pull complete
ec53a8bbdedb: Pull complete
94ffd148d107: Pull complete
3cb49b624d90: Pull complete
Digest: sha256:13a0aa8b07a6ee32a782e87a0d18646672fec672a0d64a6588b16b5b4770a97a
Status: Downloaded newer image for bryanlatten/dcos-jenkins-dind-agent:0.4.1-ubuntu
==> Launching the Docker daemon...
==> Waiting for the Docker daemon to come online...
time="2017-03-17T19:44:54.500312230Z" level=info msg="libcontainerd: new containerd process, pid: 24"
time="2017-03-17T19:44:55.550194833Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-03-17T19:44:55.551275555Z" level=info msg="Loading containers: start."
time="2017-03-17T19:44:55.554099997Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.9-coreos-r1/modules.dep.bin'\nmodprobe: WARNING: Module bridge not found in directory /lib/modules/4.9.9-coreos-r1\nmodprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.9-coreos-r1/modules.dep.bin'\nmodprobe: WARNING: Module br_netfilter not found in directory /lib/modules/4.9.9-coreos-r1\n, error: exit status 1"
time="2017-03-17T19:44:55.557831203Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.9-coreos-r1/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.9.9-coreos-r1`, error: exit status 1"
time="2017-03-17T19:44:55.559594519Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.9-coreos-r1/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.9.9-coreos-r1`, error: exit status 1"
time="2017-03-17T19:44:55.630468422Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2017-03-17T19:44:55.666769851Z" level=info msg="Loading containers: done."
time="2017-03-17T19:44:55.678338798Z" level=info msg="Daemon has completed initialization"
time="2017-03-17T19:44:55.678574670Z" level=info msg="Docker daemon" commit=60ccb22 graphdriver=overlay version=17.03.0-ce
time="2017-03-17T19:44:55.686935168Z" level=info msg="API listen on /var/run/docker.sock"
==> Docker Daemon is up and running!
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
time="2017-03-17T19:44:55.825225273Z" level=error msg="Handler for POST /v1.26/containers/create returned error: No such image: hello-world:latest"
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
78445dd45222: Pulling fs layer
78445dd45222: Verifying Checksum
78445dd45222: Download complete
78445dd45222: Pull complete
Digest: sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Review by ssk2 — APPROVED** [review]
Thanks, this looks good to me!

**Comment by ssk2** [comment]
@bryanlatten - @colin-msphere is working on a new Jenkins package - at which point he'll tag and release a new version of this container. Should be live in the next day or two. Really appreciate the contribution!

**Pull request merged**
